DataValidator/Models/DataCleansing/DCAction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mgl.DataValidator.Models.DataCleansing
{
    public abstract class DCAction
    {
        public DCAction(DataFieldDataCleansing dc)
        {
            DataFieldDataCleansing = dc;
        }
        protected DataFieldDataCleansing DataFieldDataCleansing { get; set; }

        public abstract void ExecuteAction();

        public static DCAction New(DataFieldDataCleansing dc)
        {

            switch ((EnumDCAction) dc.DCId)
            {
                case EnumDCAction.RemoveSpace:
                    return new DCRemoveSpace(dc);
                case EnumDCAction.RemoveComma:
                    return new DCRemoveComma(dc);
                case EnumDCAction.ReplaceText:
                    return new DCReplaceText(dc);
                case EnumDCAction.PadLeft:
                    return new DCPaddingLeft(dc);
                case EnumDCAction.PadRight:
                    return new DCPaddingRight(dc);
                case EnumDCAction.StringToDate:
                    return new DCStringToDate(dc);
                case EnumDCAction.Trim:
                    return new DCTrim(dc);
                case EnumDCAction.ToUppercase:
                    return new DCToUppercase(dc);
                case EnumDCAction.ToLowercase:
                    return new DCToLowerCase(dc);
                case EnumDCAction.FormatValidPhoneNO:
                    return new DCFormatValidPhoneNo(dc);
                case EnumDCAction.RegexRemoveTexts:
                    return new DCRegexRemoveTexts(dc);
                case EnumDCAction.RemoveInvalidPhoneNO:
                    return new DCRemoveInvalidPhoneNo(dc);
                case EnumDCAction.DCTrimNonAlphabetChars:
                    return new DCTrimNonAlphabetChars(dc);
                default:
                    throw new NotSupportedException("Action not supported");
            }
        }
    }
}

DataValidator/Models/DataField.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mgl.DataValidator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataField()
        {
            this.DataFieldDataCleansings = new HashSet<DataFieldDataCleansing>();
            this.DataFieldRules = new HashSet<DataFieldRule>();
            this.FileTemplateDataFields = new HashSet<FileTemplateDataField>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int FieldType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public bool Disabled { get; set; }
        public bool ExcludeFromOutput { get; set; }
        public string OutputColumnName { get; set; }
        public string XMLChildNodeXPath { get; set; }
        public bool HasMultipleNodes { get; set; }
        public bool OutputFieldOnly { get; set; }
        public int FileSection { get; set; }
        public string OutputFormat { get; set; }
        public string DefaultValue { get; set; }
        public string CoordinateForVariable { get; set; }
        public Nullable<int> FieldWidth { get; set; }
        public string DCExpression { get; set; }
        public bool Parameterize { get; set; }
        public string ParameterLabel { get; set; }
        public string ChildNodes { get; set; }
        public Nullable<int> XMLListElementId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataFieldDataCleansing> DataFieldDataCleansings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataFieldRule> DataFieldRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTemplateDataField> FileTemplateDataFields { get; set; }
    }
}

DataValidator/Models/ValidationRules/VRFieldType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mgl.DataValidator.Models.ValidationRules
{
    public class VRFieldType : VRBase
    {
        public VRFieldType(DataFieldRule df) : base(df)
        {
        }

        public override bool ValidateField()
        {
            switch ((EnumFieldType)ParentFieldRule.DataField.FieldType)
            {
                case EnumFieldType.Integer:
                    if (!int.TryParse(ParentFieldRule.DataField.OriginalValue, out int intOut))
                    {
                        AppendError();
                        return false;
                    }

                    break;
                case EnumFieldType.Decimal:
                    if (!decimal.TryParse(ParentFieldRule.DataField.OriginalValue, out decimal decOut ))
                    {
                        AppendError();
                        return false;
                    }
                    break;
                case EnumFieldType.Float:
                    if (!float.TryParse(ParentFieldRule.DataField.OriginalValue, out float fltOut))
                    {
                        AppendError();
                        return false;
                    }
                    break;
                case EnumFieldType.Boolean:
                    if (!bool.TryParse(ParentFieldRule.DataField.OriginalValue, out bool bOut))
                    {
                        AppendError();
                        return false;
                    }
                    break;
                case EnumFieldType.Date:
                    if (!DateTime.TryParse(ParentFieldRule.DataField.OriginalValue, out DateTime dtOut))
                    {
                        AppendError();
                        return false;
                    }
                    break;
                default:
                    break;
            }

            return true;
        }
    }
}

DataValidator/Models/ValidationRules/VRMandatoryField.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mgl.DataValidator.Models.ValidationRules
{
    public class VRMandatoryField : VRBase
    {
        public VRMandatoryField(DataFieldRule df) : base(df)
        {
        }

        public override bool ValidateField()
        {
            if (string.IsNullOrEmpty(this.ParentFieldRule.DataField.OriginalValue))
            {
                AppendError();
                return false;
            }
            return true;
        }
    }
}

DataValidator/Controllers/DataFieldController.cs
using Mgl.DataValidator.Models;
using Mgl.DataValidator.ViewModel;
using Security.Authorize;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Mgl.DataValidator.Controllers
{
    [ReadWriteAuthorizeUser]
    public class DataFieldController : ControllerBase
    {


        protected FileTemplateRepository _ftr;
        protected DataFieldRepository _dfr;
        protected RegExRepository _regexr;
        public DataFieldController(FileTemplateRepository ftr, DataFieldRepository dfr, RegExRepository regExr)
        {
            _ftr = ftr;
            _dfr = dfr;
            _regexr = regExr;
        }

        private const string SEARCH_PRMS = "DFSearchPrms";

        protected SearchPrms<DataField> CurrentSearchPrms
        {
            get
            {
                return this.Session[SEARCH_PRMS] == null ? null : (SearchPrms<DataField>)this.Session[SEARCH_PRMS];
            }
            set
            {
                Session.Add(SEARCH_PRMS, value);
            }
        }


        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? pageSize)
        {
            SearchPrms<DataField> searchPrms = null;

            if (string.IsNullOrEmpty(sortOrder) && string.IsNullOrEmpty(currentFilter) && string.IsNullOrEmpty(searchString)
                && !page.HasValue && !pageSize.HasValue && CurrentSearchPrms != null)
            {
                searchPrms = CurrentSearchPrms;
            }
            else
            {
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                searchPrms = new SearchPrms<DataField>(sortOrder, searchString, page, pageSize, Utility.DefaultPageSize, null);
            }

            List<DataField> dfs = null;
            User user = ((User)Session[Session.SessionID]);
            if (user.IsAdmin)
                dfs = _dfr.GetAll().Where(x => string.IsNullOrEmpty(searchPrms.SearchString) || (x.Name.Contains(searchPrms.SearchString) || x.Description.Contains(searchPrms.SearchString))).OrderByDescending(x => x.DateUpdated).ToList();
            else
            {
                if (user.AssociatedFileTemplates != null && user.AssociatedFileTemplates.Count > 0)
                {
                    List<int> ftIds = user.AssociatedFileTemplates.Select(x => x.Id).ToList();
                    dfs = _dfr.GetAll().Where(x => (string.IsNullOrEmpty(searchPrms.SearchString) || (x.Name.Contains(searchPrms.SearchString) || x.Description.Contains(searchPrms.SearchString))) && (x.FileTemplateDataFields.Any(y => ftIds.Contains(y.FileTemplateId)) || x.CreatedBy == user.Id || x.UpdatedBy == user.Id)).OrderByDescending(x => x.DateUpdated).ToList();
                }
                else
                    dfs = _dfr.GetAll().Where(x => (string.IsNullOrEmpty(searchPrms.SearchString) || (x.Name.Contains(searchPrms.SearchString) || x.Description.Contains(searchPrms.SearchString))) && (x.CreatedBy == user.Id || x.UpdatedBy == user.Id)).OrderByDescending(x => x.DateUpdated).ToList();
            }

            CurrentSearchPrms = new SearchPrms<DataField>(searchPrms.SortOrder, searchPrms.SearchString, searchPrms.PageNo, searchPrms.PageSize, Utility.DefaultPageSize, dfs);

            return View(CurrentSearchPrms).Information("Search results found: " + CurrentSearchPrms.RowsCount.ToString());
        }        

        public ActionResult Details(int id)
        {
            DataFieldViewModel vm = new DataFieldViewModel(_dfr, _dfr.GetById(id));
            return View(vm);
        }

        public ActionResult Create()
        {
            DataFieldViewModel vm = new DataFieldViewModel(_dfr, null);
            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            DataFieldViewModel vm = new DataFieldViewModel(_dfr, null);
            TryUpdateModel(vm);
            if (ModelState.IsValid)
            {
                _dfr.Create(vm.DataField);
                return RedirectToAction("Edit", new { id = vm.DataField.Id });
            }
            else
            {
                return View(vm);
            }
        }

        public ActionResult Clone(int? id)
        {
            if (id.HasValue)
            {
                DataField currentDF = _dfr.GetById(id.Value);
                DataField newDF = currentDF.Clone;
                _dfr.Create(newDF);
                return RedirectToAction("Edit", new { id = newDF.Id }).Success("Clone of " + currentDF.Name + " has been created successfully.");
            }
            return RedirectToAction("Index").Danger("Data Field failed to clone.");
        }

        public ActionResult Edit(int id)
        {
            var dataField = _dfr.GetById(id);
            if (!dataField.Editable)
                return RedirectToAction("AccessDenied", "Error");

            DataFieldViewModel vm = new DataFieldViewModel(_dfr, dataField);
            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var vm = new DataFieldViewModel(_dfr, _dfr.GetById(id));

            if (vm.DataField == null)
                throw new Exception("Data field not found with id " + id.ToString());

            if (!vm.DataField.Editable)
                return RedirectToAction("AccessDenied", "Error");

            TryUpdateModel(vm);
            if (ModelState.IsValid)
            {
                //Update the item
                _dfr.Update(vm.DataField);
                if (!string.IsNullOrEmpty(Request.Form["UrlRef"]))
                {
                    return Redirect(Request.Form["UrlRef"]).Success(vm.DataField.Name + " data field has been updated successfully");
                }
                return RedirectToAction("Index").Success(vm.DataField.Name + " data field has been updated successfully");
            }

            //Return with error
            return View(vm);
        }

        [AdminOnlyAuthorizeUser]
        public ActionResult Delete(int id)
        {
            DataField df = _dfr.GetById(id);
            if (df == null)
            {
                throw new NullReferenceException("Data field (" + id.ToString() + ") not found");
            }

            int associatedTemplates = df.FileTemplateDataFields.Where(x => x.FileTemplate.Disabled == false).Count();
            if (associatedTemplates > 0)
            {
                return RedirectToAction("Index").Danger("Failed to delete " + df.Name + " as some active file templates are referencing it.");
            }
            else
            {
                _dfr.Delete(df);
                return RedirectToAction("Index").Success(df.Name + " has been deleted successfully.");
            }
        }

        [HttpPost]
        public ActionResult SortDCActions(int id, string DCAIdList)
        {
            DataField df = _dfr.GetById(id);
            int[] orderedDCAArr = DCAIdList.Split(',').Select(x => int.Parse(x)).ToArray();
            List<DataFieldDataCleansing> dfdcs = new List<DataFieldDataCleansing>();
            foreach (var dfdcId in orderedDCAArr)
            {
                var dfdc = df.DataFieldDataCleansings.Where(x => x.Id == dfdcId).FirstOrDefault();
                if (dfdc == null)
                {
                    throw new Exception("DataFieldDataCleansing item not found with id:" + dfdcId.ToString());
                }
                dfdcs.Add(dfdc.Clone());
            }

            df = _dfr.ReorderDataFieldDataCleasning(df, dfdcs);
            return PartialView("_ActionList", df.DataFieldDataCleansings.ToList());
        }

        [HttpPost]
        public ActionResult DCActionUpdate(int? DataFieldId, int? DCId, string OldText, string NewText, string ProcessInfo, int? PaddingLength,string PaddingChar,string InputDateFormat, int? RegularExpressionId)
        {
            if ((!DataFieldId.HasValue || !DCId.HasValue)
                || ((DCId.Value == (int)EnumDCAction.ReplaceText) && (string.IsNullOrEmpty(OldText)))
                || ((DCId.Value == (int)EnumDCAction.PadLeft || DCId.Value == (int)EnumDCAction.PadRight) && (string.IsNullOrEmpty(PaddingChar) || !PaddingLength.HasValue))
                || ((DCId.Value == (int)EnumDCAction.StringToDate) && (string.IsNullOrEmpty(InputDateFormat)))
                || ((DCId.Value == (int)EnumDCAction.RegexRemoveTexts || DCId.Value == (int)EnumDCAction.RegexRemoveTexts) && (!RegularExpressionId.HasValue))
               )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DataFieldDataCleansing dc = new DataFieldDataCleansing()
            {
                DataFieldId = DataFieldId.Value,
                DCId = DCId.Value,
                OldText = OldText,
                NewText = NewText,
                PaddingLength = PaddingLength,
                PaddingChar = PaddingChar,
                InputDateFormat = InputDateFormat,
                RegularExpressionId = RegularExpressionId
            };

            if (!string.IsNullOrEmpty(ProcessInfo))
                dc.ProcessInfoId = int.Parse(ProcessInfo);

            _dfr.AddDataFieldAction(dc);

            List<DataFieldDataCleansing> actions = _dfr.GetById(DataFieldId.Value).DataFieldDataCleansings.OrderBy(x => x.Id).ToList();
            return PartialView("_ActionList", actions);

        }

        [HttpPost]
        public ActionResult DCActionDelete(int? Id)
        {
            if (!Id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DataFieldDataCleansing dc = _dfr.GetDataFieldAction(Id.Value);
            if (dc == null)

DataValidator/Views/DataField/Create.cshtml
@model Mgl.DataValidator.ViewModel.DataFieldViewModel

@{
    ViewBag.Title = "Add Data Field";
    
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">        
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row mb-2">
            <div class="col-md-6">
                <div class="form-inline">
                    @Html.LabelFor(model => model.DataField.Name, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.EditorFor(model => model.DataField.Name, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                    </div>
                </div>
                <div class="col-md-12 text-md-center">
                    @Html.ValidationMessageFor(model => model.DataField.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-inline">
                    @Html.LabelFor(model => model.DataField.FieldType, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.DropDownListFor(model => model.DataField.FieldType, EnumHelper.GetSelectList(typeof(Mgl.DataValidator.Models.EnumFieldType)), "Select a field type...", new { @class = "form-control form-control-sm" })
                    </div>
                </div>
                <div class="col-md-12 text-md-center">
                    @Html.ValidationMessageFor(model => model.DataField.FieldType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-md-6">
                <div class="form-inline">
                    @Html.LabelFor(model => model.DataField.Description, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.TextAreaFor(model => model.DataField.Description, new { @class = "form-control form-control-sm", @cols = 40, @rows = 4 })                        
                    </div>
                </div>
            </div>
        </div>
        <hr/>
        <div class="form-inline">
            <div class="col-md-offset-2">
                <input type="submit" value="Create" class="btn badge-info" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn badge-info" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DataValidator/Views/DataField/Index.cshtml
@using Mgl.DataValidator.Models
@model Mgl.DataValidator.Models.SearchPrms<DataField>
@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Data Fields";

}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Index", "DataField", FormMethod.Get, new { id = "form1" }))
{
    <div class="form-horizontal">
        <div class="row mb-1">
            <div class="col-md-8">
                <div class="form-inline">
                    @Html.LabelFor(model => model.SearchString, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.EditorFor(model => model.SearchString, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                        <input type="submit" value="Search" class="btn badge-info" />
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-inline">
                    @Html.LabelFor(model => model.PageSize, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.DropDownListFor(model => model.PageSize, Model.PageSizeList, new { @class = "form-control form-control-sm" })
                    </div>
                </div>
            </div>

        </div>

    </div>

}

@if (((User)Context.Session[HttpContext.Current.Session.SessionID]).IsAdmin)
{
    <div style="float:left; margin-top:20px">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn badge-info" })
    </div>

}
<div style="float:right">
    @Html.PagedListPager(Model.Results, page => Url.Action("Index", new { page, pageSize = Model.PageSize, sortOrder = Model.SortOrder, currentFilter = Model.SearchString, }))
</div>

<div class="table table-responsive">

    <table class="table table-sm small table-striped table-hover table-condensed">
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Output Column Name
            </th>
            <th>
                Exclude From Output
            </th>
            <th>
                XPath
            </th>
            <th>
                Field Type
            </th>
            <th>
                File Section
            </th>
            <th>
                Referenced By
            </th>
            <th style="width:7%">
                Actions
            </th>
        </tr>

        @foreach (var item in Model.Results)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayOutputColumnName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayExcludeFromOutput)
                </td>
                <td style="max-width:175px; word-wrap:break-word;">
                    @Html.DisplayFor(modelItem => item.DisplayXMLChildNodeXPath)
                </td>
                <td>
                    @((Mgl.DataValidator.Models.EnumFieldType)item.FieldType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayFileSection)
                </td>
                <td>
                    @Html.Raw(item.AssocciatedFileTemplates)
                </td>
                <td style="width:7%">
                    <div> @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "badge badge-pill badge-info" })</div>
                    @if (((User)Context.Session[HttpContext.Current.Session.SessionID]).IsAdmin)
                    {
                        <div> @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "badge badge-pill badge-info" })</div>
                    }
                    <div>@Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "badge badge-pill badge-info" })</div>
                </td>
            </tr>
        }

    </table>


</div>

<div style="margin-top:20px">
    Page @(Model.Results.PageCount < Model.Results.PageNumber ? 0 : Model.Results.PageNumber) of @Model.Results.PageCount

    @Html.PagedListPager(Model.Results, page => Url.Action("Index", new { page, pageSize = Model.PageSize, sortOrder = Model.SortOrder, currentFilter = Model.SearchString, }))

</div>


<script type="text/javascript">
    $(function () {
        $("#PageSize").change(function () {
            $("#form1").submit();
        });
    });

</script>

DataValidator/Views/DataField/_ActionList.cshtml
@model IEnumerable<Mgl.DataValidator.Models.DataFieldDataCleansing>

<div class="table-responsive">

    <table class="table table-sm table-striped table-hover table-condensed table-bordered tblDCActions">
        <tr>
            <th style="display: none;"></th>
            <th>
                DC Action
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OldText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NewText)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.ProcessInfoId)
            </th>*@
            <th>
                Actions
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="display: none;">
                    @item.Id
                </td>
                <td>
                    @item.Action.GetDisplayName()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OldText)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NewText)
                </td>
                @*<td>
                    @if (item.ProcessInfoId != null)
                    {
                      @item.ProcessInfo.GetDisplayName()
                    }                     
                </td>*@
                <td>
                    @Html.ActionLink("Delete", null, new { id = item.Id },
                 new { onclick = "return DeleteAction(" + item.Id + ")", @class="badge badge-pill badge-info" })

                </td>
            </tr>
        }

    </table>
</div>

DataValidator/Views/DataField/_VRList.cshtml
@model IEnumerable<Mgl.DataValidator.Models.DataFieldRule>

<div class="table-responsive">

    <table class="table table-sm table-striped table-hover table-condensed table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VRId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoredProcedureId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegularExpressionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReferenceListId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxFieldLength)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MinFieldLength)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TerminateIfInvalid)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.VR.GetDisplayName()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoredProcedure.SPName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegularExpression.RegExText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReferenceList.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxFieldLength)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinFieldLength)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TerminateIfInvalid)
            </td>
            <td>
                @Html.ActionLink("Delete", null, new { id = item.Id },
             new { onclick = "return DeleteVR(" + item.Id + ")", @class= "badge badge-pill badge-info" })
            </td>
        </tr>
        }

    </table>
</div>