DataValidator/Models/Entity/XsdFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using  Mgl.DataValidator.Models.ValidationRules;
using  Mgl.DataValidator.Models;
using System.Runtime.Serialization;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using System.Data.SqlClient;
using System.Data;
using System.ComponentModel.DataAnnotations;

namespace Mgl.DataValidator.Models
{
    [MetadataType(typeof(Metadata))]
    public partial class XsdFile
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [Display(Name = "Referenced By")]
        public string AssociatedFileTemplates
        {
            get
            {
                string fileNames = string.Empty;
                List<FileTemplate> fileTemplates = FileTemplates.Where(x => x.Disabled == false).ToList();
                string appPath = System.Web.HttpContext.Current.Request.ApplicationPath.TrimEnd("/".ToCharArray()) + "/FileTemplate/Details/";
                if (fileTemplates.Count > 0)
                {
                    foreach (var fileTemplate in fileTemplates)
                    {
                        fileNames = fileNames + "| <a href='" + appPath + fileTemplate.Id.ToString() + "'>" + fileTemplate.Name + "</a>";
                    }
                    fileNames = fileNames.Trim().Trim("|".ToCharArray());
                }
                return fileNames;
            }
        }

        public class Metadata
        {
            [Display(Name = "File Name")]
//            [Required(ErrorMessage = "RegEx required.")]
            public string OriginalFileName;

            [Display(Name = "Local File Name")]
            [Required(ErrorMessage = "Local File Name required.")]
            public string LocalFileName;

            [Display(Name = "XML Namespace")]
            public string XmlNameSpace;

        }
    }

}

DataValidator/Models/XsdFile.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mgl.DataValidator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XsdFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XsdFile()
        {
            this.FileTemplates = new HashSet<FileTemplate>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string OriginalFileName { get; set; }
        public string LocalFileName { get; set; }
        public string XmlNameSpace { get; set; }
        public bool Disabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTemplate> FileTemplates { get; set; }
    }
}

DataValidator/Controllers/XsdFileController.cs
using Mgl.DataValidator.Models;
using Security.Authorize;
using System.Collections.Generic;
using System.Configuration;
using System.Web;
using System.Web.Mvc;

namespace Mgl.DataValidator.Controllers
{
    [AdminOnlyAuthorizeUser]
    public class XsdFileController : ControllerBase
    {
        XsdFileRepository _efr;
        public XsdFileController(XsdFileRepository rer)
        {
            _efr = rer;
        }

        public ActionResult Index()
        {
            IEnumerable<XsdFile> regexs = _efr.GetAll();
            return View(regexs);
        }

        public ActionResult Details(int id)
        {            
            return View(_efr.GetById(id));
        }

        public ActionResult Create()
        {            
            return View(new XsdFile() { LocalFileName = "temp.xsd"});
        }

        [HttpPost]
        public ActionResult Create(XsdFile re, HttpPostedFileBase fileInput)
        {
            if (!re.OriginalFileName.ToLower().EndsWith(".xsd"))
            {
                return View(re).Warning("Invalid file type, please upload xsd file only.");
            }

            if (ModelState.IsValid)
            {
                _efr.Create(re);
                if (fileInput != null)
                {
                    string directoryPath = (ConfigurationManager.AppSettings["XSDFilePath"]).TrimEnd("\\".ToCharArray()) + "\\";
                    fileInput.SaveAs(directoryPath + re.LocalFileName);
                }

                return RedirectToAction("Index").Success("Xsd file uploaded successfully.");
            }

            return View(re);
        }

        public ActionResult Edit(int id)
        {
            return View(_efr.GetById(id));
        }


        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, HttpPostedFileBase fileInput)
        {
            XsdFile re = _efr.GetById(id);
            TryUpdateModel(re);
            if (ModelState.IsValid)
            {
                _efr.Update(re);
                if (fileInput != null)
                {
                    string directoryPath = (ConfigurationManager.AppSettings["XSDFilePath"]).TrimEnd("\\".ToCharArray()) + "\\";
                    fileInput.SaveAs(directoryPath + re.LocalFileName);
                }

                return RedirectToAction("Index").Success(re.OriginalFileName + " has been updated successfully.");
            }
            return View(re).Danger(" Failed to update the xsd file - " + re.OriginalFileName);
        }

        public ActionResult Delete(int id)
        {
                XsdFile re = _efr.GetById(id);
                if (re.FileTemplates.Count > 0 )
                {
                    return RedirectToAction("Index").Danger(re.OriginalFileName + " cannot be deleted due to the reference of other entities.");
                }
                
                _efr.Delete(re);
                return RedirectToAction("Index").Success(re.OriginalFileName + " has been deleted successfully.");
        }
    }
}

DataValidator/Views/XsdFile/Create.cshtml
@model Mgl.DataValidator.Models.XsdFile

@{
    ViewBag.Title = "Create";
    
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "XsdFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.LocalFileName)

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.XmlNameSpace, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.XmlNameSpace, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                <div class="col-md-3 badge cust-badge-light">
                    <label>Data File </label>
                </div>
                <div class="col-md-auto ">
                    <input type="file" class="form-control-file" name="fileInput" id="fileInput" aria-describedby="fileHelp">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.OriginalFileName, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.OriginalFileName, new { htmlAttributes = new { @class = "form-control form-control-sm", @readonly = "readonly" } })
                </div>
            </div>
            <div class="col-md-12 text-md-center InputFileNameVD">
                @Html.ValidationMessageFor(model => model.OriginalFileName, "Select a file to get the file name...", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <hr />
    <div class="form-inline">
        <div class="col-md-offset-2">
            <input type="submit" value="Create" class="btn badge-info btnCreateTstFT" />
            @Html.ActionLink("Back to List", "Index", null, htmlAttributes: new { @class = "btn badge-info" })
        </div>
    </div>
</div>
}

<div>
</div>


<script>
    $(document).ready(function () {
        $('.InputFileNameVD').hide();
        $('#OriginalFileName').prop('required', false);       
    });

    $('.btnCreateTstFT').click(function () {

        if ($('#OriginalFileName').val() == null || $('#OriginalFileName').val() == '') {
            $('.InputFileNameVD').show();
            $('#OriginalFileName').prop('required', true);
        }
        else {
            $('.InputFileNameVD').hide();
            $('#OriginalFileName').prop('required', false);
        }        
    });

    $('#fileInput').change(function () {
        var filePath = $(this).val();

        if (filePath != null || filePath != '') {
            var fileNameIndex = filePath.lastIndexOf('\\') + 1;
            var fileName = filePath.substr(fileNameIndex);
            $('#OriginalFileName').val(fileName);
            $('.InputFileNameVD').hide();
            $('#OriginalFileName').prop('required', false);
        }
        if (filePath == null || filePath == '') {
            $('.InputFileNameVD').show();
        }
    });


</script>

DataValidator/Views/XsdFile/Details.cshtml
@using Mgl.DataValidator.Models
@model Mgl.DataValidator.Models.XsdFile

@{
    ViewBag.Title = "Xsd File Details";

}

<h2>@ViewBag.Title</h2>
<hr />
<div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.Description, new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DisplayTextFor(model => model.Description)
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.OriginalFileName, new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DisplayTextFor(model => model.OriginalFileName)
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.XmlNameSpace, new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DisplayTextFor(model => model.XmlNameSpace)
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.LocalFileName, new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DisplayTextFor(model => model.LocalFileName)
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.Disabled, new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.Label(Model.Disabled.ToYesNo())
                </div>
            </div>
        </div>

    </div>

</div>
<hr />
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn badge-info" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn badge-info" })
</p>

DataValidator/Views/XsdFile/Edit.cshtml
@model Mgl.DataValidator.Models.XsdFile

@{
    ViewBag.Title = "Edit Xsd File";
    
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Edit", "XsdFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.LocalFileName)

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.XmlNameSpace, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.XmlNameSpace, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="form-inline">
                <div class="col-md-3 badge cust-badge-light">
                    <label>Data File </label>
                </div>
                <div class="col-md-auto ">
                    <input type="file" class="form-control-file" name="fileInput" id="fileInput" aria-describedby="fileHelp">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                @Html.LabelFor(model => model.OriginalFileName, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.OriginalFileName, new { htmlAttributes = new { @class = "form-control form-control-sm", @readonly = "readonly" } })
                </div>
            </div>
            <div class="col-md-12 text-md-center InputFileNameVD">
                @Html.ValidationMessageFor(model => model.OriginalFileName, "Select a file to get the file name...", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <hr />
    <div class="form-inline">
        <div class="col-md-offset-2">
            <input type="submit" value="Save" class="btn badge-info btnCreateTstFT" />
            @Html.ActionLink("Back to List", "Index", null, htmlAttributes: new { @class = "btn badge-info" })
        </div>
    </div>
</div>
}

<div>
</div>


<script>
    $(document).ready(function () {
        $('.InputFileNameVD').hide();
        $('#OriginalFileName').prop('required', false);       
    });

    $('.btnCreateTstFT').click(function () {

        if ($('#OriginalFileName').val() == null || $('#OriginalFileName').val() == '') {
            $('.InputFileNameVD').show();
            $('#OriginalFileName').prop('required', true);
        }
        else {
            $('.InputFileNameVD').hide();
            $('#OriginalFileName').prop('required', false);
        }        
    });

    $('#fileInput').change(function () {
        var filePath = $(this).val();

        if (filePath != null || filePath != '') {
            var fileNameIndex = filePath.lastIndexOf('\\') + 1;
            var fileName = filePath.substr(fileNameIndex);
            $('#OriginalFileName').val(fileName);
            $('.InputFileNameVD').hide();
            $('#OriginalFileName').prop('required', false);
        }
        if (filePath == null || filePath == '') {
            $('.InputFileNameVD').show();
        }
    });


</script>

DataValidator/Views/XsdFile/Index.cshtml
@using Mgl.DataValidator.Models;
@model IEnumerable<XsdFile>

@{
    ViewBag.Title = "Xsd Files";
}

<h2>@ViewBag.Title</h2>
<hr />
<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn badge-info" })
</p>
<div class="table-responsive">
    <table class="table table-sm table-striped table-hover table-condensed">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OriginalFileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.XmlNameSpace)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssociatedFileTemplates)
            </th>
            <th>
                Actions
            </th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OriginalFileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.XmlNameSpace)
            </td>
            <td>
                @Html.Raw(item.AssociatedFileTemplates)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "badge badge-pill badge-info" }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "badge badge-pill badge-info" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "badge badge-pill badge-info" })
            </td>
        </tr>
        }

    </table>
</div>