DataValidator/Controllers/SupportController.cs
using Mgl.DataValidator.Models;
using Security.Authorize;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Mgl.DataValidator.Controllers
{
    [ReadWriteAuthorizeUser]
    public class SupportController : ControllerBase
    {

        public SupportController(StoredProcedureRepository spr, UserRepository ur, EventLogRepository elr)
        {
            _spr = spr;
            _ur = ur;
            _elr = elr;
        }

        private UserRepository _ur;
        private EventLogRepository _elr;
        private StoredProcedureRepository _spr;
        private const string SEARCH_EL_PRMS = "ELSearchPrms";
        private const string SEARCH_SE_PRMS = "SESearchPrms";
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SystemErrorLog()
        {

            string[] data;
            if (System.IO.File.Exists(Utility.ErrorLogFilePath))
            {
                using (Stream stream = System.IO.File.Open(Utility.ErrorLogFilePath, FileMode.Open, FileAccess.Read,
                                        FileShare.ReadWrite))
                {
                    data = stream.ReadAllLines();
                    stream.Close();
                }

                if (data.Length > 0)
                {

                    Response.ClearHeaders();
                    Response.ContentType = "text/xml;charset=UTF-8";
                    Response.AppendHeader("content-disposition", "attachment; filename=\"SystemErrors_" + DateTime.Now.ToString("ddMMyyyyhhmmss") + ".xml\"");
                    //Response.CacheControl = "Private";
                    //Response.Cache.SetExpires(DateTime.Now.AddMinutes(3)); // or put a timestamp in the filename in the content-disposition
                    Response.Write(string.Join(Environment.NewLine, data));
                    Response.End();
                }
                else
                {
                    Response.Write("The error log file is empty.");
                    Response.Flush();
                }
            }
            else
            {
                Response.Write("The error log file does not exist.");
                Response.Flush();
            }

            return null;
        }

        protected ELSearchPrms<EventLog> CurrentELSearchPrms
        {
            get
            {
                return Session[SEARCH_EL_PRMS] == null ? null : (ELSearchPrms<EventLog>)this.Session[SEARCH_EL_PRMS];
            }
            set
            {
                Session.Add(SEARCH_EL_PRMS, value);
            }
        }

        protected SESearchPrms<SQLError> CurrentSESearchPrms
        {
            get
            {
                return Session[SEARCH_SE_PRMS] == null ? null : (SESearchPrms<SQLError>)this.Session[SEARCH_SE_PRMS];
            }
            set
            {
                Session.Add(SEARCH_SE_PRMS, value);
            }
        }

        public ActionResult SystemEventLog(string sortOrder, string currentFilter, string searchString, int? page, int? pageSize, DateTime? fromDate, DateTime? toDate, int? eventTypeId, int? userId)
        {
            ELSearchPrms<EventLog> searchPrms = null;

            if (string.IsNullOrEmpty(sortOrder) && string.IsNullOrEmpty(currentFilter) && string.IsNullOrEmpty(searchString)
                && !page.HasValue && !pageSize.HasValue && CurrentELSearchPrms != null)
            {
                searchPrms = CurrentELSearchPrms;
            }
            else
            {
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                searchPrms = new ELSearchPrms<EventLog>(sortOrder, searchString, page, pageSize, Utility.DefaultPageSize, null, fromDate, toDate, eventTypeId, userId,
                     _ur.GetAll().Select(x => new SelectListItem() { Text = x.UserId, Value = x.Id.ToString() }).OrderBy(y=> y.Text).ToList()
                    );
            }
            DateTime? toDateDummy = null;
            if (searchPrms.ToDate.HasValue)
                toDateDummy = searchPrms.ToDate.Value.AddDays(1);

            var eventLogs = _elr.GetAll(x => (string.IsNullOrEmpty(searchPrms.SearchString) || (x.FileTemplate.Name.Contains(searchPrms.SearchString))) && (!searchPrms.FromDate.HasValue || x.ProcessStartedOn >= searchPrms.FromDate.Value) && (!toDateDummy.HasValue || x.ProcessStartedOn < toDateDummy.Value) && (!searchPrms.EventTypeId.HasValue || x.Action == searchPrms.EventTypeId.Value) && (!searchPrms.UserId.HasValue || x.UserId == searchPrms.UserId.Value)).OrderByDescending(x => x.ProcessStartedOn).Take(Utility.MaxListItems);
            CurrentELSearchPrms = new ELSearchPrms<EventLog>(searchPrms.SortOrder, searchPrms.SearchString, searchPrms.PageNo, searchPrms.PageSize, Utility.DefaultPageSize, eventLogs.ToList(), searchPrms.FromDate, searchPrms.ToDate, searchPrms.EventTypeId, searchPrms.UserId, searchPrms.Users);

            return View(CurrentELSearchPrms).Information("Search results found: " + CurrentELSearchPrms.RowsCount.ToString());

        }
        [AdminOnlyAuthorizeUser]
        public ActionResult SQLErrorLog(string sortOrder, string currentFilter, string searchString, int? page, int? pageSize, DateTime? fromDate, DateTime? toDate, int? dbConnectionId)
        {
            SESearchPrms<SQLError> searchPrms = null;

            if (string.IsNullOrEmpty(sortOrder) && string.IsNullOrEmpty(currentFilter) && string.IsNullOrEmpty(searchString)
                && !page.HasValue && !pageSize.HasValue && CurrentSESearchPrms != null)
            {
                searchPrms = CurrentSESearchPrms;
            }
            else
            {
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                var dbconns = _spr.GetConnections().OrderBy(x => x.Name).ToList();

                if (!dbConnectionId.HasValue)
                    dbConnectionId = dbconns.FirstOrDefault().Id;

                searchPrms = new SESearchPrms<SQLError>(sortOrder, searchString, page, pageSize, Utility.DefaultPageSize, null, fromDate, toDate, dbConnectionId, dbconns);
            }

            FileTemplate fileTemplate = new FileTemplate()
            {
                DBConnectionId = searchPrms.DBConnectionId,
                DbConnection = searchPrms.DBConnections.Where(x => x.Id == searchPrms.DBConnectionId).FirstOrDefault()
            };

            string sqlSelect = "SELECT TOP " + Utility.MaxListItems.ToString() + " Id,ErrorNumber,Severity,State,ErrorProcedure,ErrorLine,ErrorMessage,ExecutedOn FROM[oso].[SQLErrors] " ;
            string sqlWhere = string.Empty;

            if (searchPrms.FromDate.HasValue || searchPrms.ToDate.HasValue || !string.IsNullOrEmpty(searchPrms.SearchString))
            {
                sqlWhere = " WHERE ";
                sqlWhere = sqlWhere + (searchPrms.FromDate.HasValue ? " ExecutedOn >= '" + searchPrms.FromDate.Value.ToString("yyyy-MM-dd HH:mm:ss") + "' AND" : string.Empty);
                sqlWhere = sqlWhere + (searchPrms.ToDate.HasValue ? " ExecutedOn < '" + searchPrms.ToDate.Value.AddDays(1).ToString("yyyy-MM-dd HH:mm:ss") + "' AND" : string.Empty);
                sqlWhere = sqlWhere + (!string.IsNullOrEmpty(searchPrms.SearchString) ? "(( ErrorMessage like '%" + searchPrms.SearchString.Replace("'","''") + "%') OR (ErrorProcedure like '%" + searchPrms.SearchString.Replace("'","''") + "%')) AND " : string.Empty);
                sqlWhere = sqlWhere.Trim().TrimEnd("AND".ToCharArray());
            }

            sqlSelect = sqlSelect + (!string.IsNullOrEmpty(sqlWhere) ? sqlWhere : string.Empty) + " ORDER BY ExecutedOn DESC";
            CmdText cmdText = new CmdText()
            {
                DBConnectionId = searchPrms.DBConnectionId.Value,
                DbConnection = searchPrms.DBConnections.Where(x => x.Id == searchPrms.DBConnectionId).FirstOrDefault(),
                Name = "GetSQLError",
                FileTemplate = fileTemplate,
                SQLScript = sqlSelect,
                ParamCollection = new Dictionary<string, object>()
            };

            List<SQLError> seLog = new List<SQLError>();
            DataProvider dp = DataProvider.New(fileTemplate);
            bool succeed = false;
            try
            {
                DataTable dt = dp.GetDataCmdText(cmdText);
                seLog =  dt.AsEnumerable().Select(x => new SQLError()
                  {
                      ErrorMessage = x.Field<string>("ErrorMessage"),
                      ErrorLine = x.Field<int>("ErrorLine"),
                      ErrorNumber = x.Field<int>("ErrorNumber"),
                      ErrorProcedure = x.Field<string>("ErrorProcedure"),
                      ExecutedOn = x.Field<DateTime>("ExecutedOn"),
                      Severity = x.Field<int>("Severity"),
                     State = x.Field<int>("State")

                }).ToList();
                succeed = true;
            }
            catch (Exception ex)
            {
                logger.Error(ex);
            }

            CurrentSESearchPrms = new SESearchPrms<SQLError>(searchPrms.SortOrder, searchPrms.SearchString, searchPrms.PageNo, searchPrms.PageSize, Utility.DefaultPageSize, seLog.ToList(), searchPrms.FromDate, searchPrms.ToDate, searchPrms.DBConnectionId, searchPrms.DBConnections);
            if (succeed)
                return View(CurrentSESearchPrms).Information("Search results found: " + CurrentSESearchPrms.RowsCount.ToString());

DataValidator/Views/Support/Index.cshtml
@using Mgl.DataValidator.Models

@{
    ViewBag.Title = "Support Manager";
    
}

<h2>@ViewBag.Title</h2>
<hr />
<div class="row mb-2">
    <div class="col-md-4">
        <div class="jumbotron">
            <h2>System Error Log</h2>
            <p class="lead">Download system error log</p>
            <p><a href="~/Support/SystemErrorLog" class="btn btn-info btn-lg">Download &raquo;</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="jumbotron">
            <h2>System Event Log</h2>
            <p class="lead">View system event log</p>
            <p><a href="~/Support/SystemEventLog" class="btn btn-info btn-lg">View &raquo;</a></p>
        </div>
    </div>
    @if (((User)Context.Session[HttpContext.Current.Session.SessionID]).IsAdmin)
    {
        <div class="col-md-4">
            <div class="jumbotron">
                <h2>SQL Error Log</h2>
                <p class="lead">View Columbus Sql error log</p>
                <p><a href="~/Support/SqlErrorLog" class="btn btn-info btn-lg">View &raquo;</a></p>
            </div>
        </div>
    }
    </div>

DataValidator/Views/Support/SQLErrorLog.cshtml
@using Mgl.DataValidator.Models
@model Mgl.DataValidator.Models.SESearchPrms<SQLError>
@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "SQL Error Log";

}

<div class="alert alert-warning Msg" id="actionMsg" style="opacity:1; display:none;">
</div>

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("SQLErrorLog", "Support", FormMethod.Get, new { id = "form1" }))
{
    <div class="form-horizontal">
        <div class="row mb-1">
            <div class="col-md-5">
                <div class="form-inline">
                    @Html.LabelFor(model => model.DBConnectionId, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.DropDownListFor(model => model.DBConnectionId, Model.DBConnections.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList(), new { @class = "form-control form-control-sm", @name = "DBConnectionId" })
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-inline">
                    @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control form-control-sm datepicker", @name = "FromDate", @Value = Model.FromDate.HasValue ? Model.FromDate.Value.ToString("yyyy-MM-dd") : null } })
                    </div>
                </div>
            </div>



        </div>

        <div class="row mb-1">
            <div class="col-md-5">
                <div class="form-inline">
                    @Html.LabelFor(model => model.SearchString, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.EditorFor(model => model.SearchString, new { htmlAttributes = new { @class = "form-control form-control-sm", @name = "SearchString" } })
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-inline">
                    @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control form-control-sm datepicker", @name = "ToDate", @Value = Model.ToDate.HasValue ? Model.ToDate.Value.ToString("yyyy-MM-dd") : null } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-inline">
                    @Html.LabelFor(model => model.PageSize, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                    <div class="col-md-auto">
                        @Html.DropDownListFor(model => model.PageSize, Model.PageSizeList, new { @class = "form-control form-control-sm", @name = "PageSize" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-1">
            <div class="col-md-4">
                <div class="form-inline">
                    <div class="col-md-auto">
                        <input type="submit" value="Search" class="btn badge-info" />
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div style="float:right;  margin-top:20px">
        @Html.PagedListPager(Model.Results, page => Url.Action("SQLErrorLog", new { page, pageSize = Model.PageSize, sortOrder = Model.SortOrder, currentFilter = Model.SearchString, fromDate = Model.FromDate, toDate = Model.ToDate, dbConnectionId = Model.DBConnectionId}))
    </div>
}



<div class="table-responsive">
    <table class="table table-sm table-striped table-hover table-condensed tableFTTP">
        <tr>
            <th>
                SP Name
            </th>
            <th>
                Line No.
            </th>
            <th>
                Error Description
            </th>
            <th>
                Executed On
            </th>
            <th>
                Error No.
            </th>
            <th>
                Severity
            </th>
            <th>
                State
            </th>
        </tr>

        @foreach (var item in Model.Results)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ErrorProcedure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ErrorLine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ErrorMessage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExecutedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ErrorNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Severity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
        </tr>
        }

    </table>
</div>

<div style="margin-top:20px">
    Page @(Model.Results.PageCount < Model.Results.PageNumber ? 0 : Model.Results.PageNumber) of @Model.Results.PageCount

    @Html.PagedListPager(Model.Results, page => Url.Action("SQLErrorLog", new { page, pageSize = Model.PageSize, sortOrder = Model.SortOrder, currentFilter = Model.SearchString, fromDate = Model.FromDate, toDate = Model.ToDate, dbConnectionId = Model.DBConnectionId }))

</div>


<script type="text/javascript">
        $(function () {
            $("#PageSize").change(function () {
                $("#form1").submit();
            });
        });

</script>

DataValidator/Views/Support/SystemEventLog.cshtml
@using Mgl.DataValidator.Models
@model Mgl.DataValidator.Models.ELSearchPrms<EventLog>
@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "System Event Log";

}

<div class="alert alert-warning Msg" id="actionMsg" style="opacity:1; display:none;">
</div>

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("SystemEventLog", "Support", FormMethod.Get, new { id = "form1" }))
{
<div class="form-horizontal">
    <div class="row mb-1">
        <div class="col-md-4">
            <div class="form-inline">
                @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DropDownListFor(model => model.UserId, Model.Users, "Select an user ...", new { @class = "form-control form-control-sm", @name = "UserId" })
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-inline">
                @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control form-control-sm datepicker", @name = "FromDate", @Value = Model.FromDate.HasValue ? Model.FromDate.Value.ToString("yyyy-MM-dd") : null } })
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div class="form-inline">
                @Html.LabelFor(model => model.EventTypeId, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DropDownListFor(model => model.EventTypeId, EnumHelper.GetSelectList(typeof(Mgl.DataValidator.Models.EnumDataFileScreen)), "Select an event type...", new { @class = "form-control form-control-sm", @name = "EventTypeId" })
                </div>
            </div>
        </div>



    </div>

    <div class="row mb-1">
        <div class="col-md-4">
            <div class="form-inline">
                @Html.LabelFor(model => model.SearchString, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.SearchString, new { htmlAttributes = new { @class = "form-control form-control-sm", @name = "SearchString" } })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-inline">
                @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control form-control-sm datepicker", @name = "ToDate", @Value = Model.ToDate.HasValue ? Model.ToDate.Value.ToString("yyyy-MM-dd") : null } })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-inline">
                @Html.LabelFor(model => model.PageSize, htmlAttributes: new { @class = "badge cust-badge-light col-md-3" })
                <div class="col-md-auto">
                    @Html.DropDownListFor(model => model.PageSize, Model.PageSizeList, new { @class = "form-control form-control-sm", @name = "PageSize" })
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-1">
        <div class="col-md-8">
            <div class="form-inline">
                <div class="col-md-auto">
                    <input type="submit" value="Search" class="btn badge-info" />
                </div>
            </div>
        </div>

    </div>
</div>

<div style="float:right;  margin-top:20px">
    @Html.PagedListPager(Model.Results, page => Url.Action("SystemEventLog", new { page, pageSize = Model.PageSize, sortOrder = Model.SortOrder, currentFilter = Model.SearchString, fromDate = Model.FromDate, toDate = Model.ToDate, eventTypeId = Model.EventTypeId, userId = Model.UserId }))
</div>
}



    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover table-condensed tableFTTP">
            <tr>
                <th>
                    User Name
                </th>
                <th>
                    IP Address
                </th>
                <th>
                    File Template
                </th>
                <th>
                    Action
                </th>
                <th>
                    Input File
                </th>
                <th>
                    Started On
                </th>
                <th>
                    Ended On
                </th>
                <th>
                    Succeeded
                </th>
                <th>
                    Note
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.UserId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IPAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileTemplate.Name)
                    </td>
                    <td>
                        @(((Mgl.DataValidator.Models.EnumDataFileScreen)item.Action).GetDisplayName())
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProcessStartedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProcessEndedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Succeeded)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Note)
                    </td>
                </tr>
            }

        </table>
    </div>

    <div style="margin-top:20px">
        Page @(Model.Results.PageCount < Model.Results.PageNumber ? 0 : Model.Results.PageNumber) of @Model.Results.PageCount

        @Html.PagedListPager(Model.Results, page => Url.Action("SystemEventLog", new { page, pageSize = Model.PageSize, sortOrder = Model.SortOrder, currentFilter = Model.SearchString, fromDate = Model.FromDate, toDate = Model.ToDate, eventTypeId = Model.EventTypeId, userId = Model.UserId }))

    </div>


    <script type="text/javascript">
        $(function () {
            $("#PageSize").change(function () {
                $("#form1").submit();
            });
        });

    </script>